const state={snapshot:null,platforms:[],models:[],hardware:null,schedule:null,jobs:[],artifacts:{logs:[],reports:[]},editing:null,logins:new Map()};
const $=(selector,root=document)=>root.querySelector(selector);const $$=(selector,root=document)=>[...root.querySelectorAll(selector)];

document.addEventListener("DOMContentLoaded",init);
async function init(){bind();tick();setInterval(tick,30000);connectEvents();await refreshAll();}
function bind(){
  $("#nav").addEventListener("click",e=>{const button=e.target.closest("[data-page]");if(button)showPage(button.dataset.page)});
  document.addEventListener("click",e=>{const link=e.target.closest("[data-page-link]");if(link)showPage(link.dataset.pageLink);if(e.target.closest("[data-refresh]"))refreshAll()});
  $("#run-now").onclick=()=>action(async()=>{await api("/api/runs",{method:"POST",body:{previousDay:true}});notice("日报任务已进入后台队列")});
  $("#add-source").onclick=()=>{$("#source-detect-url").value="";openSource()};$("#source-search").oninput=renderSources;$("#source-platform-filter").onchange=renderSources;
  $("#source-detect").onclick=()=>action(detectSourceFromUrl);
  $$('[data-close-source]').forEach(button=>button.onclick=()=>{$("#source-dialog").close();state.editing=null});
  $("#source-platform").onchange=renderSourceFields;$("#source-form").onsubmit=saveSource;
  $("#source-grid").onclick=sourceAction;$("#account-grid").onclick=accountAction;$("#model-grid").onclick=modelAction;
  $("#check-all").onclick=()=>action(async()=>{state.platforms=await api("/api/platforms?probe=true");renderAccounts();renderDashboard();notice("登录状态检测完成")});
  $("#hardware-check").onclick=()=>action(loadHardware);$("#schedule-install").onclick=()=>action(saveSchedule);$("#schedule-remove").onclick=()=>action(removeSchedule);
  $("#email-save").onclick=()=>action(saveEmail);$("#email-test").onclick=()=>action(async()=>{await api("/api/email/test",{method:"POST"});notice("测试邮件正在后台发送")});
  $("#config-save").onclick=()=>action(saveAdvanced);$("#config-reload").onclick=()=>action(loadConfig);
  $("#artifacts").onclick=artifactAction;
}
async function refreshAll(){await action(async()=>{await loadConfig();renderAll()},{quiet:true});await Promise.allSettled([
  api("/api/platforms").then(value=>{state.platforms=value;renderAccounts();renderSources();renderDashboard()}),
  api("/api/models").then(value=>{state.models=value;renderModels();renderDashboard()}),
  api("/api/schedule").then(value=>{state.schedule=value;renderSchedule()}),
  api("/api/runs").then(value=>{state.jobs=value.jobs;state.artifacts=value.artifacts;renderRuns();renderDashboard()}),
  loadHardware()
])}
async function loadConfig(){state.snapshot=await api("/api/config");fillConfig();}
async function loadHardware(render=true){state.hardware=await api("/api/hardware");if(render)renderModels();}
function renderAll(){renderDashboard();renderSources();renderAccounts();renderModels();renderSchedule();renderRuns();fillConfig();}

async function detectSourceFromUrl(){
  const detected=await api("/api/sources/detect",{method:"POST",body:{url:$("#source-detect-url").value}});
  $("#source-platform").value=detected.platform;$("#source-name").value=detected.displayName;$("#source-id").value=detected.id;
  renderSourceFields(detected);notice("已识别平台和主页标识，请确认显示名称");
}

function showPage(name){$$('[data-page]').forEach(b=>b.classList.toggle("active",b.dataset.page===name));$$('.page').forEach(p=>p.classList.toggle("active",p.id===`page-${name}`));const titles={dashboard:["今日状态","信息汇聚，一目了然"],sources:["内容入口","管理你的关注"],accounts:["身份与健康","平台账号"],models:["LOCAL AI","转录模型中心"],schedule:["AUTOMATION","定时任务"],delivery:["SMTP","邮件投递"],runs:["OBSERVABILITY","运行记录"],advanced:["CONFIG.JSON","高级配置"]};$("#eyebrow").textContent=titles[name][0];$("#page-title").textContent=titles[name][1];}
function renderDashboard(){const sources=state.snapshot?.config.sources??[];const valid=state.platforms.filter(p=>["valid","not_needed"].includes(p.session?.status)).length;const installed=state.models.filter(m=>m.installed).length;const last=state.jobs[0];$("#metrics").innerHTML=[metric("关注来源",sources.filter(s=>s.enabled!==false).length,`${sources.length} 个已配置`),metric("平台健康",`${valid}/${state.platforms.length}`,"主动检测可刷新"),metric("本地模型",installed,last?.type==="model-install"&&last.status==="running"?"正在下载":"离线转录"),metric("最近日报",state.artifacts.reports?.length??0,last?statusLabel(last.status):"暂无任务")].join("");$("#health-list").innerHTML=state.platforms.map(p=>`<div class="health-item"><div><b>${esc(p.displayName)}</b><small class="card-meta"> ${capabilityText(p)}</small></div>${badge(p.session?.status,p.session?.message)}</div>`).join("");$("#recent-jobs").innerHTML=jobsHtml(state.jobs.slice(0,5));}
function metric(label,value,note){return `<div class="metric"><small>${label}</small><strong>${esc(value)}</strong><small>${esc(note)}</small></div>`}
function renderSources(){const platformFilter=$("#source-platform-filter"),selectedPlatform=platformFilter.value;platformFilter.innerHTML=`<option value="">全部平台</option>${state.platforms.map(p=>`<option value="${esc(p.id)}">${esc(p.displayName)}</option>`).join("")}`;platformFilter.value=state.platforms.some(p=>p.id===selectedPlatform)?selectedPlatform:"";const query=$("#source-search").value.trim().toLowerCase(),platform=platformFilter.value;const sources=(state.snapshot?.config.sources??[]).filter(s=>s.displayName.toLowerCase().includes(query)&&(!platform||s.platform===platform));$("#source-count").textContent=`${sources.length} 个来源`;$("#source-grid").innerHTML=sources.length?sources.map(s=>`<article class="source-card"><div class="platform-icon">${platformGlyph(s.platform)}</div><h3>${esc(s.displayName)}</h3><p class="card-meta">${esc(platformName(s.platform))} · ${esc(s.id)}</p><p class="card-meta">${esc(s.url??s.feedUrl??"")}</p>${badge(s.enabled===false?"expired":"valid",s.enabled===false?"已停用":"已启用")}<div class="card-actions"><button class="secondary" data-source-edit="${esc(s.id)}">编辑</button><button class="secondary" data-source-toggle="${esc(s.id)}">${s.enabled===false?"启用":"停用"}</button><button class="danger" data-source-delete="${esc(s.id)}">删除</button></div></article>`).join(""):'<p class="empty">还没有匹配的关注来源。</p>';}
function renderAccounts(){$("#account-grid").innerHTML=state.platforms.map(p=>{const login=state.logins.get(p.id),canLogin=p.capabilities.login||p.capabilities.loginOptional,optionalLabel=p.capabilities.loginOptional&&p.session?.status==="not_needed"?"公开内容可用":undefined;return `<article class="account-card"><div class="platform-icon">${platformGlyph(p.id)}</div><h3>${esc(p.displayName)}</h3><p class="card-meta">${esc(p.session?.message??"")}</p>${badge(p.session?.status,optionalLabel)}<div class="card-actions">${canLogin?login?`<button class="primary" data-login-complete="${p.id}">登录完成，保存</button>`:`<button class="primary" data-login="${p.id}">${p.capabilities.loginOptional?"登录以访问会员内容":"打开登录窗口"}</button>`:""}<button class="secondary" data-check="${p.id}">主动检测</button></div></article>`}).join("")}
function renderModels(){const h=state.hardware;if(h){$("#hardware").innerHTML=[hw("GPU",h.gpu.available?h.gpu.name:"未检测到"),hw("显存",h.gpu.available?`${Math.round(h.gpu.vramMb/1024)} GB`:"CPU 模式"),hw("模型盘可用",formatBytes(h.disk.freeBytes)),hw("Python",h.python.available?h.python.version:"未安装")].join("")}$("#model-grid").innerHTML=state.models.map(m=>`<article class="model-card ${m.selected?"selected":""}"><div class="model-title"><div><p class="eyebrow">${esc(m.provider)} · ${esc(m.version)}</p><h3>${esc(m.name)}</h3></div>${badge(m.selected?"valid":m.installed?"unknown":"expired",m.selected?"当前使用":m.installed?"已安装":"未安装")}</div><p class="card-meta">多语言语音识别 · 本地运行 · ${esc(m.backend)}</p><div class="model-specs"><div><small>预计磁盘</small><b>${formatBytes(m.estimatedBytes)}</b></div><div><small>最低显存</small><b>${m.minimumVramGb} GB</b></div><div><small>推荐切片</small><b>${m.recommendedChunkSeconds/60} 分钟</b></div></div><p class="card-meta">${esc(m.directory)}</p><div class="card-actions">${!m.installed?`<button class="primary" data-model-install="${m.id}">下载模型</button>`:!m.selected?`<button class="primary" data-model-select="${m.id}">设为默认</button>`:""}${m.installed&&!m.selected?`<button class="danger" data-model-remove="${m.id}">卸载</button>`:""}</div></article>`).join("")}
function hw(label,value){return `<div><small>${label}</small><b>${esc(value)}</b></div>`}
function renderSchedule(){const s=state.schedule??{};$("#schedule-time").value=state.snapshot?.config.reportTime??"00:30";$("#schedule-status").innerHTML=[detail("支持状态",s.supported?"Windows Task Scheduler":"当前系统不支持"),detail("任务",s.installed?"已安装":"未安装"),detail("运行状态",s.state??"—"),detail("下次运行",dateText(s.nextRunTime)),detail("上次结果",s.lastTaskResult??"—")].join("")}
function renderRuns(){$("#all-jobs").innerHTML=jobsHtml(state.jobs);const reports=state.artifacts.reports??[],logs=state.artifacts.logs??[];$("#artifacts").innerHTML=[...reports.map(a=>artifact("report",a)),...logs.map(a=>artifact("log",a))].join("")||'<p class="empty">暂无日报或日志。</p>';}
function jobsHtml(jobs){return jobs.length?jobs.map(j=>`<div class="timeline-item"><div><b>${esc(jobName(j.type))}</b><small class="card-meta">${dateText(j.startedAt||j.createdAt)} · ${esc(j.message||"")}</small>${j.status==="running"?`<div style="width:180px;height:4px;background:#eee;margin-top:7px"><i style="display:block;height:100%;background:#1f684b;width:${j.progress}%"></i></div>`:""}</div>${badge(j.status)}</div>`).join(""):'<p class="empty">暂无后台任务。</p>'}
function artifact(type,a){return `<button data-artifact-type="${type}" data-artifact-name="${encodeURIComponent(a.name)}"><b>${esc(a.name)}</b><small class="card-meta">${dateText(a.modifiedAt)} · ${formatBytes(a.size)}</small></button>`}
function fillConfig(){if(!state.snapshot)return;$("#revision").textContent=`revision ${state.snapshot.revision}`;$("#config-editor").value=JSON.stringify(state.snapshot.config,null,2);const e=state.snapshot.config.email??{};$("#email-host").value=e.host??"";$("#email-port").value=e.port??465;$("#email-user").value=e.username??"";$("#email-to").value=e.to?.[0]??"";$("#email-from").value=e.from??"";$("#email-enabled").checked=e.enabled===true;}

function openSource(source){state.editing=source?.id??null;$("#source-dialog-title").textContent=source?"编辑关注":"添加关注";$("#source-platform").innerHTML=state.platforms.map(p=>`<option value="${p.id}">${esc(p.displayName)}</option>`).join("");$("#source-platform").value=source?.platform??state.platforms[0]?.id;$("#source-platform").disabled=Boolean(source);$("#source-name").value=source?.displayName??"";$("#source-id").value=source?.id??"";$("#source-enabled").checked=source?.enabled!==false;renderSourceFields(source);$("#source-dialog").showModal();}
function renderSourceFields(source={}){const platform=state.platforms.find(p=>p.id===$("#source-platform").value);$("#source-fields").innerHTML=(platform?.fields??[]).map(f=>f.type==="boolean"?`<label class="toggle-line"><input data-source-field="${f.name}" type="checkbox" ${source[f.name]?"checked":""}>${esc(f.label)}</label>`:`<label class="${f.name==="url"||f.name==="feedUrl"?"span-2":""}">${esc(f.label)}<input data-source-field="${f.name}" type="${f.type==="url"?"url":"text"}" value="${esc(source[f.name]??"")}" ${f.required?"required":""}></label>`).join("")}
async function saveSource(e){e.preventDefault();if(e.submitter?.value==="cancel"){state.editing=null;$("#source-dialog").close();return}await action(async()=>{const source={platform:$("#source-platform").value,displayName:$("#source-name").value,id:$("#source-id").value,enabled:$("#source-enabled").checked};$$('[data-source-field]').forEach(input=>source[input.dataset.sourceField]=input.type==="checkbox"?input.checked:input.value);const url=state.editing?`/api/sources/${encodeURIComponent(state.editing)}`:"/api/sources";state.snapshot=await api(url,{method:state.editing?"PUT":"POST",body:{source,revision:state.snapshot.revision}});$("#source-dialog").close();renderAll();notice("关注来源已保存")})}
async function sourceAction(e){const id=e.target.dataset.sourceEdit||e.target.dataset.sourceToggle||e.target.dataset.sourceDelete;if(!id)return;const source=state.snapshot.config.sources.find(s=>s.id===id);if(e.target.dataset.sourceEdit)return openSource(source);if(e.target.dataset.sourceDelete&&!confirm(`确定删除“${source.displayName}”吗？`))return;await action(async()=>{state.snapshot=await api(`/api/sources/${encodeURIComponent(id)}`,{method:e.target.dataset.sourceDelete?"DELETE":"PUT",body:e.target.dataset.sourceDelete?{revision:state.snapshot.revision}:{source:{enabled:source.enabled===false},revision:state.snapshot.revision}});renderAll();notice("来源配置已更新")})}
async function accountAction(e){const platform=e.target.dataset.login||e.target.dataset.loginComplete||e.target.dataset.check;if(!platform)return;await action(async()=>{if(e.target.dataset.login){const login=await api(`/api/platforms/${platform}/login`,{method:"POST"});state.logins.set(platform,login);notice("登录窗口已打开，完成后回到这里保存")}else if(e.target.dataset.loginComplete){const login=state.logins.get(platform);const status=await api(`/api/platforms/${platform}/login/${login.id}/complete`,{method:"POST"});state.logins.delete(platform);state.platforms.find(p=>p.id===platform).session=status;notice(status.status==="valid"?"登录已保存并验证":"已保存，但未通过登录检测",status.status!=="valid")}else{state.platforms.find(p=>p.id===platform).session=await api(`/api/platforms/${platform}/check-session`,{method:"POST"})}renderAccounts();renderDashboard()})}
async function modelAction(e){const id=e.target.dataset.modelInstall||e.target.dataset.modelSelect||e.target.dataset.modelRemove;if(!id)return;if(e.target.dataset.modelRemove&&!confirm("确定卸载这个模型吗？模型文件将从磁盘删除。"))return;await action(async()=>{if(e.target.dataset.modelInstall){await api(`/api/models/${id}/install`,{method:"POST"});notice("模型下载已在后台开始")}else if(e.target.dataset.modelSelect){state.snapshot=await api(`/api/models/${id}/select`,{method:"POST",body:{revision:state.snapshot.revision}});await reloadModels();notice("默认转录模型已更新")}else{await api(`/api/models/${id}`,{method:"DELETE"});await reloadModels();notice("模型已卸载")}})}
async function reloadModels(){state.models=await api("/api/models");renderModels()}
async function saveSchedule(){const at=$("#schedule-time").value;state.schedule=await api("/api/schedule",{method:"PUT",body:{at}});const cfg=structuredClone(state.snapshot.config);cfg.reportTime=at;state.snapshot=await api("/api/config",{method:"PUT",body:{config:cfg,revision:state.snapshot.revision}});renderSchedule();notice("统一计划任务已安装")}
async function removeSchedule(){if(!confirm("确定取消每日自动任务吗？手动运行仍然可用。"))return;state.schedule=await api("/api/schedule",{method:"DELETE"});renderSchedule();notice("计划任务已取消")}
async function saveEmail(){const cfg=structuredClone(state.snapshot.config);cfg.email={...cfg.email,enabled:$("#email-enabled").checked,host:$("#email-host").value,port:Number($("#email-port").value),username:$("#email-user").value,to:[$("#email-to").value].filter(Boolean),from:$("#email-from").value};state.snapshot=await api("/api/config",{method:"PUT",body:{config:cfg,revision:state.snapshot.revision}});const secret=$("#email-secret").value;if(secret){await api("/api/email/secret",{method:"POST",body:{password:secret}});$("#email-secret").value=""}fillConfig();notice("邮件设置已保存")}
async function saveAdvanced(){const config=JSON.parse($("#config-editor").value);state.snapshot=await api("/api/config",{method:"PUT",body:{config,revision:state.snapshot.revision}});renderAll();notice("配置已校验并原子保存")}
async function artifactAction(e){const b=e.target.closest("[data-artifact-name]");if(!b)return;const data=await api(`/api/artifacts/${b.dataset.artifactType}/${b.dataset.artifactName}`);$("#artifact-title").textContent=data.name;$("#artifact-content").textContent=data.content;$("#artifact-dialog").showModal()}

function connectEvents(){
  const events=new EventSource("/api/events");
  events.addEventListener("snapshot",e=>{state.jobs=JSON.parse(e.data);renderRuns();renderDashboard()});
  events.addEventListener("job",async e=>{const job=JSON.parse(e.data);const index=state.jobs.findIndex(j=>j.id===job.id);if(index>=0)state.jobs[index]=job;else state.jobs.unshift(job);renderRuns();renderDashboard();if(job.status==="completed"&&job.type==="model-install")await reloadModels()});
  events.addEventListener("config",async e=>{const incoming=JSON.parse(e.data);if(state.snapshot&&incoming.revision!==state.snapshot.revision){await loadConfig();renderAll();notice("检测到配置文件已在外部更新，页面已重载")}});
}
async function api(url,{method="GET",body}={}){const response=await fetch(url,{method,headers:body?{"Content-Type":"application/json"}:{},body:body?JSON.stringify(body):undefined});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error??`HTTP ${response.status}`);return payload}
async function action(fn,{quiet=false}={}){try{return await fn()}catch(error){notice(error.message,true);if(!quiet)throw error}}
function notice(message,error=false){const n=$("#notice");n.textContent=message;n.className=`notice${error?" error":""}`;clearTimeout(notice.timer);notice.timer=setTimeout(()=>n.classList.add("hidden"),5000)}
function badge(status="unknown",label){return `<span class="status ${esc(status)}" title="${esc(label??"")}">${esc(label??statusLabel(status))}</span>`}
function detail(label,value){return `<div class="detail-row"><span>${label}</span><b>${esc(value)}</b></div>`}
function capabilityText(p){if(p.capabilities.login)return"需要登录";if(p.capabilities.loginOptional)return"公开内容无需登录；如需访问会员内容，请登录";if(p.capabilities.service)return p.capabilities.service;return"无需登录"}
function platformName(id){return state.platforms.find(p=>p.id===id)?.displayName??id}function platformGlyph(id){return({x:"𝕏",weibo:"微",wechat:"微",youtube:"▶",bilibili:"哔",xiaoyuzhou:"播"})[id]??"·"}
function statusLabel(v){return({valid:"正常",not_needed:"无需登录",unknown:"待检测",expired:"需登录",error:"异常",queued:"排队中",running:"执行中",completed:"完成",failed:"失败"})[v]??v??"未知"}function jobName(v){return({pipeline:"日报流水线","model-install":"模型下载","email-test":"邮件测试"})[v]??v}
function dateText(v){if(!v||v==="0001-01-01T00:00:00")return"—";const d=new Date(v);return Number.isNaN(d)?String(v):d.toLocaleString("zh-CN",{timeZone:"Asia/Shanghai",hour12:false})}function formatBytes(v){if(!Number.isFinite(Number(v)))return"—";return Number(v)>=1024**3?`${(v/1024**3).toFixed(1)} GB`:`${(v/1024**2).toFixed(0)} MB`}
function tick(){$("#clock").textContent=new Date().toLocaleString("zh-CN",{timeZone:"Asia/Shanghai",hour12:false})+" 北京时间"}function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[c])}
